scheduler:
  num_train_timesteps: 1000
  num_inference_steps: 50
  beta_schedule: "squaredcos_cap_v2"
  clip_sample: False

inference:
  batch_size: 1

dataset:
  knn: 6
  category: "NoNoise" # NoNoise, LowNoise, MedNoise, HighNoise

model:
  model_dim: 64
  attention: True
  model_path: runs/20241121-090525/model.pth