scheduler:
  num_train_timesteps: 1000
  num_inference_steps: 50
  beta_schedule: "squaredcos_cap_v2"
  clip_sample: False

training:
  n_epochs: 6000
  min_training_timestep: 0
  lr: 1e-3
  batch_size: 4

inference:
  batch_size: 1

dataset:
  knn: 6
  category: "NoNoise" # NoNoise, LowNoise, MedNoise, HighNoise

model:
  model_dim: 64
  attention: True