scheduler:
  num_train_timesteps: 1000
  num_inference_steps: 50
  beta_schedule: "squaredcos_cap_v2"
  clip_sample: False

training:
  n_epochs: 1
  lr: 1e-3
  batch_size: 8

inference:
  batch_size: 19

dataset:
  knn: 6